# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 346)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LW_products = QtWidgets.QListWidget(self.centralwidget)
        self.LW_products.setMinimumSize(QtCore.QSize(200, 0))
        self.LW_products.setObjectName("LW_products")
        self.horizontalLayout_2.addWidget(self.LW_products)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.LE_name = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LE_name.setFont(font)
        self.LE_name.setObjectName("LE_name")
        self.verticalLayout.addWidget(self.LE_name)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.LE_url = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LE_url.setFont(font)
        self.LE_url.setObjectName("LE_url")
        self.verticalLayout.addWidget(self.LE_url)
        self.CHB_track = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CHB_track.setFont(font)
        self.CHB_track.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CHB_track.setObjectName("CHB_track")
        self.verticalLayout.addWidget(self.CHB_track)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem1)
        self.PB_enter = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_enter.setFont(font)
        self.PB_enter.setObjectName("PB_enter")
        self.verticalLayout.addWidget(self.PB_enter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PB_clear = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_clear.setFont(font)
        self.PB_clear.setObjectName("PB_clear")
        self.horizontalLayout.addWidget(self.PB_clear)
        self.PB_change = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_change.setFont(font)
        self.PB_change.setObjectName("PB_change")
        self.horizontalLayout.addWidget(self.PB_change)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.PB_plot = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_plot.setFont(font)
        self.PB_plot.setObjectName("PB_plot")
        self.verticalLayout.addWidget(self.PB_plot)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 21))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.action_agent = QtWidgets.QAction(MainWindow)
        self.action_agent.setObjectName("action_agent")
        self.action_fetch_price = QtWidgets.QAction(MainWindow)
        self.action_fetch_price.setObjectName("action_fetch_price")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.menuOptions.addAction(self.action_agent)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.action_fetch_price)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.action_exit)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Amazon Price Tracker"))
        self.label_4.setText(_translate("MainWindow", "Amazon Price Tracker and Graph Plotter"))
        self.label_3.setText(_translate("MainWindow", "Enter the short product name / description as well as the link of it. You can also set Products as inactive to not longer checks them every day."))
        self.label.setText(_translate("MainWindow", "Short Name:"))
        self.label_2.setText(_translate("MainWindow", "Product URL:"))
        self.CHB_track.setText(_translate("MainWindow", "Track this Product"))
        self.PB_enter.setText(_translate("MainWindow", "Enter"))
        self.PB_clear.setText(_translate("MainWindow", "Clear"))
        self.PB_change.setText(_translate("MainWindow", "Change"))
        self.PB_plot.setText(_translate("MainWindow", "Plot the Price Graph"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.action_agent.setText(_translate("MainWindow", "select User Agent"))
        self.action_agent.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_fetch_price.setText(_translate("MainWindow", "fetch price for product"))
        self.action_fetch_price.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.action_exit.setText(_translate("MainWindow", "Exit program"))
        self.action_exit.setShortcut(_translate("MainWindow", "Ctrl+X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

